#ifndef PROJECTILE_CONFIG_H
#define PROJECTILE_CONFIG_H

#define PROJ_NINJA_STAR		  115	
#define PROJ_ELECTRIC_SHOCK	  18	
#define PROJ_FLAME_BALL       27
#define PROJ_TOWER_BOT_BULLET 13 
#define PROJ_SENTRY_BULLET    15 
#define PROJ_ELITE_PISTOL_BULLET 16
#define PROJ_ELITE_RIFLE_BULLET 17
#define PROJ_PRISONER_ROCK 10
#define PROJ_GRENADE 33
#define PROJ_GRENADE_EXPLOSION 34
#define PROJ_GRENADE_FLAK 35
#define PROJ_PROJECTILE 32
#define PROJ_G_MONSTER_SPIT 12
#define PROJ_JUNKBOT_WALKING_BULLET 14
#define PROJ_JUNKBOT_LARGE_ROCK  13
#define PROJ_GROUND_WAVE 11
#define PROJ_CRASH_ROCKET_BASIC 9
#define PROJ_CRASH_ROCKET_ADVANCED 10
#define PORJ_CRASH_GRENADE_1 12
#define PROJ_CRASH_BULLET 13
#define PROJ_CRASH_FLAK 14
#define PROJ_CRASH_G_EXPLOSION 15
#define PROJ_JUNKBOT_FLYING 15
#define PROJ_KNIFE 13
#define PROJ_WRENCH 16
#define PROJ_JACOB_FLAME_BALL 11
#define PROJ_JACOB_STONE 9
#define PROJ_JACOB_SHOCK_ATTACK 10
#define PROJ_BUBBLE 70
#endif
